--- 
before_script: 
  - "yarn"
cache: ~
language: node_js
node_js: 
  - "10.16.3"
jobs:
  include:
    -stage: lint
    name: "Lint"
    script: npm run lint

    -stage: test
    name: "Test"
    script: npm run build

    -stage: build
    name: "Build"
    script: npm run build
cache:
  yarn: true

